---
title: "Time Series 7 Time series regression models"
author: "Yuzhou Peng"
date: "2023-10-07"
output: html_document
---

### Example: US consumption expenditure
```{r}
library(fpp3)
data("us_change")
us_change %>%
  pivot_longer(c(Consumption, Income), names_to = "Series") %>%
  autoplot(value) +
  labs(y = "% change")
```
A scatter plot of consumption changes against income changes is shown in Figure 7.3 along with the estimated regression line
```{r}
us_change %>%
  ggplot(aes(x = Income, y = Consumption)) +
  labs(y = "Consumption (quarterly % change)",
       x = "Income (quarterly % change)") +
  geom_point() +
  geom_smooth(method = "lm")
```
The equation is estimated using the **TSLM()** function
```{r}
us_change %>%
  model(TSLM(Consumption ~ Income)) %>%
  report()
```
Multiple variables regression
```{r}
fit_consMR <- us_change %>%
  model(tslm = TSLM(Consumption ~ Income + Production + Unemployment + Savings))

report(fit_consMR)
```

### Fitted values
```{r}
augment(fit_consMR) %>%
  ggplot(aes(x = Quarter)) +
  geom_line(aes(y = Consumption, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted")) +
  labs(y = NULL,
    title = "Percent change in US consumption expenditure"
  ) +
  scale_colour_manual(values=c(Data="black",Fitted="#D55E00")) +
  guides(colour = guide_legend(title = NULL))

augment(fit_consMR) %>%
  ggplot(aes(x = Consumption, y = .fitted)) +
  geom_point() +
  labs(
    y = "Fitted (predicted values)",
    x = "Data (actual values)",
    title = "Percent change in US consumption expenditure"
  ) +
  geom_abline(intercept = 0, slope = 1)
```

### 7.3 Evaluating the regression model
### 7.4 Some useful predictors